// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TorchMessage.proto

package magshimim.torchmobile.networking.protos;

public final class TorchMessageOuterClass {
  private TorchMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ByteArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:torch.ByteArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code torch.ByteArray}
   */
  public  static final class ByteArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:torch.ByteArray)
      ByteArrayOrBuilder {
    // Use ByteArray.newBuilder() to construct.
    private ByteArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ByteArray() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ByteArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_ByteArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_ByteArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.class, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray)) {
        return super.equals(obj);
      }
      magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray other = (magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code torch.ByteArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:torch.ByteArray)
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_ByteArray_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_ByteArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.class, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder.class);
      }

      // Construct using magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_ByteArray_descriptor;
      }

      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray getDefaultInstanceForType() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.getDefaultInstance();
      }

      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray build() {
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray buildPartial() {
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray result = new magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray(this);
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray) {
          return mergeFrom((magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray other) {
        if (other == magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:torch.ByteArray)
    }

    // @@protoc_insertion_point(class_scope:torch.ByteArray)
    private static final magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray();
    }

    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ByteArray>
        PARSER = new com.google.protobuf.AbstractParser<ByteArray>() {
      public ByteArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ByteArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ByteArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ByteArray> getParserForType() {
      return PARSER;
    }

    public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TorchMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:torch.TorchMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.torch.TorchMessage.MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.torch.TorchMessage.MessageType type = 1;</code>
     */
    magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType getType();

    /**
     * <code>.torch.ByteArray frame = 2;</code>
     */
    boolean hasFrame();
    /**
     * <code>.torch.ByteArray frame = 2;</code>
     */
    magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray getFrame();
    /**
     * <code>.torch.ByteArray frame = 2;</code>
     */
    magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArrayOrBuilder getFrameOrBuilder();
  }
  /**
   * Protobuf type {@code torch.TorchMessage}
   */
  public  static final class TorchMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:torch.TorchMessage)
      TorchMessageOrBuilder {
    // Use TorchMessage.newBuilder() to construct.
    private TorchMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TorchMessage() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TorchMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder subBuilder = null;
              if (frame_ != null) {
                subBuilder = frame_.toBuilder();
              }
              frame_ = input.readMessage(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(frame_);
                frame_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_TorchMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_TorchMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.class, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code torch.TorchMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FRAME = 0;</code>
       */
      FRAME(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FRAME = 0;</code>
       */
      public static final int FRAME_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return FRAME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:torch.TorchMessage.MessageType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.torch.TorchMessage.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.torch.TorchMessage.MessageType type = 1;</code>
     */
    public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType getType() {
      magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType result = magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType.valueOf(type_);
      return result == null ? magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType.UNRECOGNIZED : result;
    }

    public static final int FRAME_FIELD_NUMBER = 2;
    private magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray frame_;
    /**
     * <code>.torch.ByteArray frame = 2;</code>
     */
    public boolean hasFrame() {
      return frame_ != null;
    }
    /**
     * <code>.torch.ByteArray frame = 2;</code>
     */
    public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray getFrame() {
      return frame_ == null ? magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.getDefaultInstance() : frame_;
    }
    /**
     * <code>.torch.ByteArray frame = 2;</code>
     */
    public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArrayOrBuilder getFrameOrBuilder() {
      return getFrame();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType.FRAME.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (frame_ != null) {
        output.writeMessage(2, getFrame());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType.FRAME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (frame_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFrame());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage)) {
        return super.equals(obj);
      }
      magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage other = (magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (hasFrame() == other.hasFrame());
      if (hasFrame()) {
        result = result && getFrame()
            .equals(other.getFrame());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasFrame()) {
        hash = (37 * hash) + FRAME_FIELD_NUMBER;
        hash = (53 * hash) + getFrame().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code torch.TorchMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:torch.TorchMessage)
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_TorchMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_TorchMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.class, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.Builder.class);
      }

      // Construct using magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (frameBuilder_ == null) {
          frame_ = null;
        } else {
          frame_ = null;
          frameBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.internal_static_torch_TorchMessage_descriptor;
      }

      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage getDefaultInstanceForType() {
        return magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.getDefaultInstance();
      }

      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage build() {
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage buildPartial() {
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage result = new magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage(this);
        result.type_ = type_;
        if (frameBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = frameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage) {
          return mergeFrom((magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage other) {
        if (other == magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasFrame()) {
          mergeFrame(other.getFrame());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.torch.TorchMessage.MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.torch.TorchMessage.MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.torch.TorchMessage.MessageType type = 1;</code>
       */
      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType getType() {
        magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType result = magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType.valueOf(type_);
        return result == null ? magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.torch.TorchMessage.MessageType type = 1;</code>
       */
      public Builder setType(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.torch.TorchMessage.MessageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray frame_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArrayOrBuilder> frameBuilder_;
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public boolean hasFrame() {
        return frameBuilder_ != null || frame_ != null;
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray getFrame() {
        if (frameBuilder_ == null) {
          return frame_ == null ? magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.getDefaultInstance() : frame_;
        } else {
          return frameBuilder_.getMessage();
        }
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public Builder setFrame(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray value) {
        if (frameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          frame_ = value;
          onChanged();
        } else {
          frameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public Builder setFrame(
          magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder builderForValue) {
        if (frameBuilder_ == null) {
          frame_ = builderForValue.build();
          onChanged();
        } else {
          frameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public Builder mergeFrame(magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray value) {
        if (frameBuilder_ == null) {
          if (frame_ != null) {
            frame_ =
              magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.newBuilder(frame_).mergeFrom(value).buildPartial();
          } else {
            frame_ = value;
          }
          onChanged();
        } else {
          frameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public Builder clearFrame() {
        if (frameBuilder_ == null) {
          frame_ = null;
          onChanged();
        } else {
          frame_ = null;
          frameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder getFrameBuilder() {
        
        onChanged();
        return getFrameFieldBuilder().getBuilder();
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArrayOrBuilder getFrameOrBuilder() {
        if (frameBuilder_ != null) {
          return frameBuilder_.getMessageOrBuilder();
        } else {
          return frame_ == null ?
              magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.getDefaultInstance() : frame_;
        }
      }
      /**
       * <code>.torch.ByteArray frame = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArrayOrBuilder> 
          getFrameFieldBuilder() {
        if (frameBuilder_ == null) {
          frameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArray.Builder, magshimim.torchmobile.networking.protos.TorchMessageOuterClass.ByteArrayOrBuilder>(
                  getFrame(),
                  getParentForChildren(),
                  isClean());
          frame_ = null;
        }
        return frameBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:torch.TorchMessage)
    }

    // @@protoc_insertion_point(class_scope:torch.TorchMessage)
    private static final magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage();
    }

    public static magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TorchMessage>
        PARSER = new com.google.protobuf.AbstractParser<TorchMessage>() {
      public TorchMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TorchMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TorchMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TorchMessage> getParserForType() {
      return PARSER;
    }

    public magshimim.torchmobile.networking.protos.TorchMessageOuterClass.TorchMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_torch_ByteArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_torch_ByteArray_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_torch_TorchMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_torch_TorchMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TorchMessage.proto\022\005torch\"\031\n\tByteArray" +
      "\022\014\n\004data\030\001 \001(\014\"x\n\014TorchMessage\022-\n\004type\030\001" +
      " \001(\0162\037.torch.TorchMessage.MessageType\022\037\n" +
      "\005frame\030\002 \001(\0132\020.torch.ByteArray\"\030\n\013Messag" +
      "eType\022\t\n\005FRAME\020\000BJ\n\'magshimim.torchmobil" +
      "e.networking.protos\252\002\036TorchDesktop.Netwo" +
      "rking.Protosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_torch_ByteArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_torch_ByteArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_torch_ByteArray_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_torch_TorchMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_torch_TorchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_torch_TorchMessage_descriptor,
        new java.lang.String[] { "Type", "Frame", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
